CREATE TABLE TauxTva(
id INT IDENTITY(1, 1) CONSTRAINT PK_TauxTva PRIMARY KEY,
taux FLOAT
)

CREATE TABLE Fabriquant(
id INT IDENTITY(1, 1) CONSTRAINT PK_Fabriquant PRIMARY KEY,
Name VARCHAR(100) NOT NULL
)

CREATE TABLE Rayon(
id INT IDENTITY(1, 1) CONSTRAINT PK_Rayon PRIMARY KEY,
ref VARCHAR(10)
)

CREATE TABLE Product(
id INT IDENTITY(1, 1) CONSTRAINT PK_Product PRIMARY KEY,
id_TauxTva INT CONSTRAINT FK_Product_TauxTva FOREIGN KEY REFERENCES TauxTva(id),
id_Fabriquant INT,
id_Rayon INT,
EAN CHAR(13),
price MONEY,
CONSTRAINT FK_Product_Fabriquant FOREIGN KEY(id_Fabriquant) REFERENCES Fabriquant(id),
CONSTRAINT FK_Product_Rayon FOREIGN KEY(id_Rayon) REFERENCES Rayon(id)
)